---
title: "New Readings"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


These are some proposed new readings for the class for Fall 2018


Seeto, Dewey, Chi-Keung Woo, and Ira Horowitz. "Time-of-use rates vs. Hopkinson tariffs redux: An analysis of the choice of rate structures in a regulated electricity distribution company." Energy Economics 19.2 (1997): 169-185.


Joskow, Paul, and Jean Tirole. "Reliability and competitive electricity markets." The Rand Journal of Economics 38.1 (2007): 60-84.

Couture, Toby, and Yves Gagnon. "An analysis of feed-in tariff remuneration models: Implications for renewable energy investment." Energy policy 38.2 (2010): 955-965.

Woo, Chi-Keung, Brian Horii, and Ira Horowitz. "The Hopkinson tariff alternative to TOU rates in the Israel Electric Corporation." Managerial and Decision Economics 23.1 (2002): 9-19.

Joskow, Paul L. "Creating a smarter US electricity grid." The Journal of Economic Perspectives 26.1 (2012): 29-47.

Joskow, Paul L., and Catherine D. Wolfram. "Dynamic pricing of electricity." The American Economic Review 102.3 (2012): 381-385.

Sensfuß, Frank, Mario Ragwitz, and Massimo Genoese. "The merit-order effect: A detailed analysis of the price effect of renewable electricity generation on spot market prices in Germany." Energy policy 36.8 (2008): 3086-3094.

Kverndokk, Snorre, Knut Einar Rosendahl, and Thomas F. Rutherford. "Climate policies and induced technological change: Which to choose, the carrot or the stick?." Environmental and Resource Economics 27.1 (2004): 21-41.

Rogers, Jennifer, Sari Fink, and Kevin Porter. Examples of wind energy curtailment practices. No. NREL/SR-550-48737. National Renewable Energy Laboratory (NREL), Golden, CO., 2010.
