---
title: "Syllabus EC438/538 Fall 2016"
author: "James Woods"
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course Description

The official description of the course is:

> Economics and structure of energy markets, with a focus on electricity. Examines current policy issues arising from energy production and use.

Since I am teaching this course for the first time, there will be changes from previous terms and I will be making official changes in description and prerequisites during the year.  

This is a companion course to EC 437/537 which will address regulatory and competitive policies in electricity, public transportation, water, natural,  and telecommunications.  The order of the courses has changed to reflect the evolving nature of the field.

<!-- ## New Kind of Slash Course -->

<!-- Students that have been at PSU for a while are familiar with "slash courses" where both undergraduates and graduate students are in the same classroom but have different assignments, readings and standards.  This course take it another step.  Undergraduate will meet in Mondays and Wednesdays and graduate students will meet on Mondays and Friday. In short, we will be together on Monday. Undergraduates will meet alone on Wednesday and Graduate students will meet alone on Friday.  All students may attend all sessions if they wish.  This arrangement should allow the graduate students to explore topics in more depth. -->

## Prerequisites

The undergraduate section has microeconomic theory, EC 311, or the calculus based version, EC 415, listed as prerequisites.  The graduate section requires only graduate standing.

As with most economics courses, the more background you bring to the class, the more get from the class.  For this class, it means bringing a background in microeconomic theory and econometrics.  Not all students will have a background in both and many of the graduate students from outside of economics will have neither.  Any technical skills that students are missing will be supplemented with in-class tutorials.  Sometimes this will mean learning about constrained optimization or breaking out laptops for a tutorial on running regressions in R.

## Key Dates

+ Last day to drop or change grade option: November 13th
+ Holidays: November 11th, 24th and 25th.

# Contact Information

The best ways of contacting me, in decreasing order of effectiveness:

+ IM/hangout: woodsj@pdx.edu
+ Phone/text: (503) 465-4883
+ Email:woodsj@pdx.edu (Answered only on M W and F)
+ D2L email: Do not use.  I will not respond.

You are encouraged to use the IM function of your PSU email account, or text, rather than email. This will allow me to get back to you more quickly and more conversationally. Please be aware that I will likely not reply till the next day if you IM me after 5pm or on the weekend.  

Office Hours:

+ My office is in CH 241-O.
+ Drop in office hours are Monday 2:30-3:30 pm  through the last week of class. There is no need to make an appointment for these hours -- just come.
+ If you can’t attend regular office hours, please check my calendar https://woodsj.youcanbook.me/. I will make a limited number of 20 minute slots available each week.  

# Textbook and Other Resources

The main text for the course is Dahl, Carol. _International Energy Markets: Understanding Pricing, Policies, & Profits._ PennWell Books, 2015.  It was chosen undergraduates in mind and illustrates many of the concepts they learned in EC 311/415. 

This text will be heavily supplemented with material from the Energy Information Administration (EIA), the textbook authors website, and journal articles available electronically through the library.

# Assessments and Grade Policy

This class will be taught as a collaborative seminar with limited traditional lecture. There are no exams but
there will be a considerable amount of writing and analysis, presentations by teams of student researchers
and several referee reports. Nearly all work product will be made public to the class, though your grade will not.

+ Various Team Assignments in total: 25%
+ Final Draft of Term Paper: 20%
+ Draft Term Paper: 15%
+ Presentation of Paper Topic: 15%
+ Annotated Bibliography: 3%
+ Abstract: 2%
+ Referee Report(s) of Draft Paper(s): 15%
+ Referee Report(s) of Final Paper(s): 5%

Term papers, referee reports and bibliographies will be turned in a D2L dropbox as a pdf or a link to a google doc with PSU log in and granted comment privileges.  Malfunctioning links or corrupted files will be interpreted as a missed deadline and receive half the normal credit if corrected within 24 hrs. If a deadline is missed by more than 24 hrs, zero credit will be given.  While this seems harsh, missing a deadline means that other students have less time to complete their work.

## Regular Team Assignments

Teams will be assigned by the instructor after the first week of class. They will be composed of at least one
graduate student and one undergraduate student. Assignments will be made based a survey of completed
math, economics and statistics courses. The intent is to ensure that each team has the skills it needs to
succeed.

The teams are intended to encourage cooperative learning where graduate students can assist undergraduate
students with concepts they are unsure of and those with exceptional skills can share insight with
others.

A team may remove a member by an anonymous 3/4th majority vote of a current members. Removed
members will act as a team of one until other teams remove members or students join the class. Removed
members may join other teams by an anonymous 3/4th majority vote of the receiving team. All votes will
be conducted by the instructor should two students on a team request a vote. The instructor reserves the
right to reassign students to teams should there be large differences in team size.

Regular team assignments will be a diverse selection of activities that will range from creating a day ahead electricity forecast, explaining a crack spread with current data, or just sorting out a nasty diagram in the book.

Grad students will also be formed into teams for assignments that are specific to them.

## Individual/Group Term Paper

The largest assignment will be a term paper. The term paper may be
either a literature review, in which case it must be completed by an individual, or an empirical/theoretical
paper which may have up to three co-authors. Graduate students
must complete an empirical/theoretical paper. Term paper preparation and evaluation will be in stages.

1. Authors and co-authors must publish an abstract, including a few key references, in the “Draft Abstracts”
dropbox in D2L by _October 24th_. Students will have a 30 minute review meeting with the instructor during that week. These meetings will be scheduled in class on October 17th. Scope and depth changes will be agreed to in the meeting.

2. A revised abstract must be submitted by _October 28th_ and will be published in the “Final Abstracts”
dropbox in D2L. Abstracts will be discussed in class on October 30th. Ideally, two reviewers will be
assigned to each paper and no reviewer will be assigned more than one paper, but this may not happen depending on the balance of single and multi-author papers.

3. Authors and co-authors will construct an annotated bibliography. A reasonably complete annotated bibliography will be submitted in D2L by _November 4th_ and should be provided in “Bibliography” dropbox in D2L.  Here are some links on how to create an annotated bibliography, http://guides.library.cornell.edu/annotatedbibliography and               https://www.bethel.edu/library/research/apa-annobib-sixth.pdf 


4. Authors and co-authors that are pursuing an empirical paper must schedule a 20-minute presentation
to the class on data collection, design and analysis approach prior to completion of the draft paper.  These presentation will be scheduled to take place from _Nov 7th through the November 16th_ unless the author team wants to schedule something earlier.
Additional problem solving presentations are encouraged. Students conducting a literature review should schedule a similar session for a key papers in their literature review. 

5. A draft of the paper must be published in the “Draft Papers” dropbox in D2L by _5 pm on November 18th_. If you are writing an empirical paper, the submission should include a link to your data and the code used to analyze the data. The professor will distribute a copy to referees. The referees will deliver a referee report on your draft by _November 23rd_  to the "Referee Report of Draft Paper" D2L dropbox.
The instructor will make additional comments after the reports are received.

6. The final paper must be published to the “Final Papers” dropbox in D2L by _December 2nd at 8pm_. Term papers
must be less than 20 pages.  The submission must include a separate document addressing the reviewers issues with the draft paper stating how the point is either irrelevant or how it is addressed in the paper.

## Referee Reports

A referee report is a critical examination of an academic paper.  There is a split in their purpose, help the editor make a determination or help the author, but in either case, you typically make the deepest read of an academic paper when you review it.  The official guidance from the AEA is (https://www.aeaweb.org/content/file?id=222) but there is some more detailed guidance here that is more helpful to authors (http://are.berkeley.edu/courses/ARE251/2004/assignments/RRGuidelines.pdf).

All referee reports will be distributed to authors.  These reports have 5pm deadlines so they can be distributed to the authors that evening.

+ A referee report on a student’s or group’s draft paper. You will be assigned a paper to review. The
report must be less than five pages. This is due by _5pm on November 23rd_ and must be submitted to "Referee Report of Draft Paper" D2L dropbox .

+ A referee report on a student’s or group’s final paper. This will be a second review of the paper you
previously reviewed. The report must be less than five pages. This referee report will be delivered by,
_by 5 pm on December 8th_ and must be submitted to "Referee Report of Final Paper" D2L dropbox.  

The reports will be evaluated on a 0 to 5 scale with the following rubric.

  + 0 Points Base
  + 1 Points Rudimentary synopsis and minor criticism of the paper.
  + 2 Points Report gives an accurate synopsis of paper and the contribution it makes to the literature.
  + 3 Points 2 AND identifies and explains weaknesses in the analysis or gaps in the literature.
  + 4 Points 3 AND provides suggested articles to be included and several options that would improve
analysis.
  + 5 Points Exemplary example of 4.


# Topics and Readings

Do not let this section alarm you.  We will only address part of this outline in the class. As with most of my upper-division courses, we will complete a small subset at the start of the class and then vote on each succeeding topic. Each topic will have an assignment, usually working with real data or using a model from the readings.

Each topic has some readings that both undergraduates and graduate students will read and some that are specific to each. Note that some of these modules will be shared with the Public Utility Economics course and I will be adding optional topics and supplementary readings throughout the term.

+ Introduction of Core Topics
    + Starting on Topic   
        + "Energy Primer: A Handbook of Energy Market Basics", FERC, 2015 (http://www.ferc.gov/market-oversight/guide/energy-primer.pdf), Chapter 1
        + Dahl, Ch 1-2.
    + Coal
        + Dahl, Ch 3.
        + Murray, Michael P.. 2006. "Avoiding Invalid Instruments and Coping with Weak Instruments." Journal of Economic Perspectives, 20(4): 111-132. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.20.4.111
    + Natural Gas
        + Dahl, Ch 8.
        + Energy Primer, Ch 2.
        + Joskow, Paul L.. 2013. "Natural Gas: From Shortages to Abundance in the United States." American Economic Review, 103(3): 338-43. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/aer.103.3.338
        + Culver, Walter J., and Mingguo Hong. "Coal’s decline: Driven by policy or technology?." The Electricity Journal 29.7 (2016): 50-61. http://www.sciencedirect.com/science/article/pii/S104061901630121X
    + Electricity
        + Energy Primer, Ch 3. 
        + Dahl, Ch 5-6.   
        + Joskow, Paul L. "Markets for power in the United States: An interim assessment." The Energy Journal, Vol. 27, No. 1. http://economics.mit.edu/files/1184
        + Joskow, Paul L.. 2012. "Creating a Smarter U.S. Electricity Grid." Journal of Economic Perspectives, 26(1): 29-48. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.26.1.29
        + Covert, Thomas, Michael Greenstone and Christopher R. Knittel. 2016. "Will We Ever Stop Using Fossil Fuels?" Journal of Economic Perspectives, 30(1): 117-38. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.30.1.117
        + Borenstein, Severin. 2012. "The Private and Public Economics of Renewable Electricity Generation." Journal of Economic Perspectives, 26(1): 67-92. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.26.1.67
        + Puller, Steven L. and Jeremy West. 2013. "Efficient Retail Pricing in Electricity and Natural Gas Markets." American Economic Review, 103(3): 350-55. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/aer.103.3.350
    + Oil
        + Dahl, Ch 7.
        + Energy Primer, Ch 4.
        + Smith, James L.. 2009. "World Oil: Market or Mayhem?" Journal of Economic Perspectives, 23(3): 145-64. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.23.3.145
        + Baumeister, Christiane and Lutz Kilian. 2016. "Forty Years of Oil Price Fluctuations: Why the Price of Oil May Still Surprise Us." Journal of Economic Perspectives, 30(1): 139-60. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.30.1.139
    
+ Topic Options, Voted on in Class
    + Financial Markets
        + Energy Primer, Ch 5.
        + Dahl, Ch 18 - 19.
        + Knittel, Christopher R. and Robert S. Pindyck. 2016. "The Simple Economics of Commodity Price Speculation." American Economic Journal: Macroeconomics, 8(2): 85-110. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/mac.20140033
        + Deng, Shi-Jie, and Shmuel S. Oren. "Electricity derivatives and risk management." Energy 31.6 (2006): 940-953. http://stats.lib.pdx.edu/proxy.php?url=http://www.sciencedirect.com/science/article/pii/S0360544205000496
    + Intro to Externalities and Public Goods
        + Dahl, Ch 11 - 12.
        + Viscusi, W. Kip, Joseph E. Harrington, and John M. Vernon. Economics of regulation and antitrust. MIT press, 2005., Ch 21 http://search.library.pdx.edu/PSU:all:CP71189149050001451
        + Metcalf, Gilbert E.. 2009. "Market-Based Policy Options to Control U.S. Greenhouse Gas Emissions." Journal of Economic Perspectives, 23(2): 5-27. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.23.2.5
    + Natural Gas Outside the US
        + Dahl, Ch 9 - 10.   
        + "International Energy Outlook", 2016, EIA, Ch 3. (https://www.eia.gov/forecasts/ieo/nat_gas.cfm)
    + Price Controls and Subsidies (Not Carbon Taxes and Implicit Subsidies)
        + Dahl, Ch 4   
        + Implementing Energy Subsidy Reforms Evidence from Developing Countries, Maria Vagliasindi, Washington : World Bank Publications 2012, Overview with countries devided between groups. http://search.library.pdx.edu/PSU:all:CP71205489150001451
    + Market Monitoring
        + Energy Primer, Ch 6.
        + Helman, Udi. "Market power monitoring and mitigation in the US wholesale power markets." Energy 31.6 (2006): 877-904. http://stats.lib.pdx.edu/proxy.php?url=http://dx.doi.org/10.1016/j.energy.2005.05.011
    + Hotelling's Rule and Dynamic Extraction
        + Dahl, Ch 14
        + Gaudet, Gérard. "Natural resource economics under the rule of Hotelling." Canadian Journal of Economics/Revue canadienne d'économique 40.4 (2007): 1033-1059. http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2966.2007.00441.x/full
    + Supply and Cost Curves
        + Dahl Ch 15
        
    + Energy Demand
        + Dahl Ch 16
        + Allcott, Hunt and Michael Greenstone. 2012. "Is There an Energy Efficiency Gap?" Journal of Economic Perspectives, 26(1): 3-28. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/jep.26.1.3
        + Dubin, Jeffrey A., and McFadden Daniel L. "An Econometric Analysis of Residential Electric Appliance Holdings and Consumption." Econometrica 52.2 (1984): 345-62. http://stats.lib.pdx.edu/proxy.php?url=http://www.jstor.org/stable/1911493
        + David R. Kamerschen, David V. Porter, The demand for residential, industrial and total electricity, 1973–1998, Energy Economics, Volume 26, Issue 1, January 2004, Pages 87-100, http://stats.lib.pdx.edu/proxy.php?url=http://dx.doi.org/10.1016/S0140-9883(03)00033-1
        + RESIDENTIAL ENERGY CONSUMPTION SURVEY (RECS), EIA. https://www.eia.gov/consumption/residential/index.cfm We will use this as an example of end use modeling as well as survey data collection and estimation.
        
    + Distributed Generation and Microgrids
        + Federal Energy Regulatory Commission. "The potential benefits of distributed generation and rate-related issues that may impede their expansion." USDOE,(Ed.) (2007). https://www.ferc.gov/legal/fed-sta/exp-study.pdf
        +


The course requires a term paper.  It is a good idea to do some broad reading to see the breadth of topics in energy economics, which roughly means the economic effects of using and generating energy.  Here are some sources for keeping up on current events and research topics.

+ A list of energy related glossaries http://dahl.mines.edu/GlossaryLinks.pdf.  Some of the links are 404 but the one at the California Energy Commission is pretty good.
+ EIA Today in Energy (https://www.eia.gov/todayinenergy/) New topics every day.
+ Journals that focus on energy economics issues
    + Energy Economics http://www.journals.elsevier.com/energy-economics/
    + The Energy Journal https://www.jstor.org/journal/energyj
    + Resource and Energy Economics http://www.journals.elsevier.com/resource-and-energy-economics/
    + Energy: The International Journal has economics and engineering http://www.journals.elsevier.com/energy/
    + Energy Policy http://www.journals.elsevier.com/energy-policy/
    + Utilities Policy for more electricity focused reading http://www.journals.elsevier.com/utilities-policy/

+ Working Paper Sources
    + IDEAS has a curated weekly summary of energy working papers https://ideas.repec.org/n/nep-ene/
    + r/EconPapers has a weekly summary of working papers from National Bureau of Economic Research (NBER).  They usually lead with energy and natural resource economics https://www.reddit.com/r/EconPapers.
    
+ The Journal of Economic Perspectives (https://www.jstor.org/journal/jeconpers) has many easy to read symposia and review articles.  Here are a few from the last decade or so. Some of these are already included in the readings.
    + SYMPOSIUM: OIL AND GAS MARKETS WINTER 2016 (https://www.jstor.org/stable/i40149800)
    + SYMPOSIUM: TRADING POLLUTION PERMITS WINTER 2013 (https://www.jstor.org/stable/i40086192)
    + SYMPOSIUM: ENERGY CHALLENGES WINTER 2012 (https://www.jstor.org/stable/i40064264)
    + SYMPOSIUM: CLIMATE CHANGE SPRING 2009 (https://www.jstor.org/stable/i27740519)

+ Data
    + OpenEI http://en.openei.org/wiki/Main_Page
    + EIA https://www.eia.gov Just go to a topic and look for the data tab.
    + Quandl https://www.quandl.com/ Has data on many topics and is an easy way to bring in macroeconomic data.
    


# Other Rules

+ Begging for grades will result in an immediate lowering of your course grade by a full letter grade.
  
+ When completing assignments *The work must be authentically and genuinely your own or group. In other words, if you are copying answers you found online, it is not your work.*
  
+ Go to office hours at the first sign of trouble -- not as a last resort.

+ In this classroom, we support and value diversity.  To do so requires that we:

    + Respect the dignity and essential worth of all individuals
    + Promote a culture of respect toward all individuals
    + Respect the privacy, property, and freedom of others
    + Reject bigotry, discrimination, violence, or intimidation of any kind
    + Practice personal and academic integrity and expect it from others
    + Promote the diversity of opinions, ideas, and backgrounds, which is the lifeblood of a university

   For additional information, please see the Office of Affirmative Action \& Equal Opportunity at http://www.pdx.edu/diversity/affirmative-action.


+ Accommodations are collaborative efforts between students, faculty, and the Disability Resource Center.  If you have a documented disability and require accommodation, you must arrange to meet with the course instructor prior to or within the first week of the term.  The documentation of your disability must come in writing from the Disability Resource Center (Faculty letter).  Students who believe they are eligible for accommodations but who have not yet obtained approval through the DRC should contact the DRC immediately.  Reasonable and appropriate accommodations will be provided for students with documented disabilities.  For more information on the Disability Resource Center, please see http://www.drc.pdx.edu. 

+ Academic honesty is expected and required of students enrolled in this course.  Suspected academic dishonesty in this course will be handled according to the procedures set out in the Student Code of Conduct.

+ I am sympathetic to family emergencies but you must inform me as soon as possible. If the notice is verbal, please email me with your understanding of our agreement. All agreements have to be in writing.

Link to this syllabus https://github.com/woodsjam/Course-Energy-Economics. Check branch for this term.
