---
title: "Assignment 1"
author: "working title"
date: "October 7, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
Coal <- read.csv("https://www.eia.gov/totalenergy/data/browser/csv.cfm?tbl=T06.01")

library(dplyr)
CoalProduction <- Coal %>% filter(MSN == "CLPRPUS")
library(stringr)
CoalProduction <- CoalProduction %>% filter(str_sub(as.character(YYYYMM),5 ) == "13")
CoalProduction <- CoalProduction %>% select(YYYYMM, Value)
names(CoalProduction) <- c("RawYear", "ProductionKShortTon")
CoalProduction$ProductionKShortTon <- as.numeric(as.character(CoalProduction$ProductionKShortTon))
CoalProduction <- CoalProduction  %>% mutate(Year = as.numeric(str_sub(as.character(RawYear),0,4 )))
library(Quandl)
CPI <- Quandl("UIFS/CPI_USA")
Prices <- Quandl("EPI/152")

summary(CPI)
summary(Prices)
 
CoalProduction$RawYear <- as.numeric(str_sub(CoalProduction$RawYear,0,4))
CPI$Date <- as.numeric(str_sub(CPI$Date,0,4))
names(CoalProduction) <- c("Year", "ProductionKShortTon", "RawYear")
CoalProduction$RawYear <- NULL
names(CPI) <- c("Year", "CPI Value", "% change")

summary(CoalProduction)

CoalProduction <- inner_join(CPI, CoalProduction, by = "Year")
summary(CoalProduction)
Prices$Year <- as.numeric(str_sub(Prices$Year,0,4))
names(Prices) <- c("Year", "Price")
CoalMarket <- inner_join(Prices, CoalProduction, by ="Year")

summary(CoalMarket)

library(dplyr)
CoalMarket$Price <- ((CoalMarket$Price)*1.13)/1000
CoalMarket$ProductionKShortTon <- ((CoalMarket$ProductionKShortTon)/1000
names(CoalMarket) <- c("Year", "Price", "CPI Value", "% Change", "ProductionShortTon")

#Years 1973 to 1977 are excluded due to oil crisis (OPEC market manipulaion)
CoalMarket$OPEC_Years <- factor(with(CoalMarket, ifelse((Year > 1972  & Year < 1978), 0, 1)))

#Before OPEC market manipulation
CoalRegressionA <-  lm(Price ~ ProductionShortTon +I(Year<1973), data = CoalMarket)
plot((CoalMarket$Price)[(CoalMarket$Year)<1973], (CoalMarket$ProductionShortTon)[(CoalMarket$Year)<1973], xlab="Price", ylab="Production Short Ton", main= "Before 1973")
plot(CoalRegressionA)
summary(CoalRegression)

#After OPEC market manipulation
CoalRegressionB <-  lm(Price ~ ProductionShortTon +I(Year>1978), data = CoalMarket)
plot((CoalMarket$Price)[(CoalMarket$Year)>1978], (CoalMarket$ProductionShortTon)[(CoalMarket$Year)>1978], xlab="Price", ylab="Production Short Ton", main= "After 1978")
plot(CoalRegressionB)
summary(CoalRegressionB)

```

