---
title: "Energy Economics Term Paper: Requirements and Guidance"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The largest assignment will be a term paper. The term paper may be
either a literature review, in which case it _must_ be completed by an individual, or an empirical/theoretical paper which may have up to three co-authors. Graduate students
must complete an empirical/theoretical paper. Term paper preparation and evaluation will be in stages.

The general parameters are that the final term paper should be between 15 and 20 pages long, excluding major graphics and bibliography.  Literature review papers should have at least 15 peer reviewed or government publications as part of the review.


## The Writing Sample

Your FRINQ and SINQ courses should have given you a foundation in more formal and academic writing, but it does not always stick.

Each student will produce a document of at least a page but no more than two, excluding the bibliography, that cites at least two source sources correctly and intentionally does not cite a source for something that should have a citation.  Following the bibliography you should explain what was uncited and how it should have been cited.

The topic should be vaguely energy related and the works cited don't have to be heavy handed.  I'm still waiting for someone to cite, "The Watchmen" or "There Will be Blood".

This should be turned in the “Writing Sample” assignment folder in D2L by _October 2nd at 5pm_.

If things are properly cited and the language is reasonable fluid -- you get full credit.  

If things are not properly cited, you still get full credit, but all the deadlines except the final draft due date are up to one week earlier.  The intent is to give you an extra week between when I return the draft papers and when you have to turn in the final paper.  The earlier deadlines are given in parenthesis below and in the syllabus.

## Key Dates and Requirements

1. Authors and co-authors must publish an abstract, including a few key references, in the “Draft Abstracts” assignment folder in D2L by _October 18th (October 14th) at 5pm_. 

1. Students will schedule a 20 minute review meeting with the instructor the following week. Meetings must be completed by _October 23rd (October 20th) at 5pm_. Scope and depth changes will be agreed to in the meeting.

1. A revised abstract must be submitted by _October 28th (Oct 22) at 5pm_ in the “Revised Abstracts”
assignment folder in D2L. Abstracts will be discussed in class on October 30th. 

1. Authors and co-authors will construct an annotated bibliography. A reasonably complete annotated bibliography will be submitted in D2L by  _November 6th (October 30th)  at 5pm_ in the “Bibliography” assignment folder.  Here are some links on how to create an annotated bibliography, http://guides.library.cornell.edu/annotatedbibliography and               https://www.bethel.edu/library/research/apa-annobib-sixth.pdf 

1. Authors must schedule a 20-minute presentation to the class on data collection, design and analysis approach prior to completion of the draft paper.  Students conducting a literature review should schedule a similar session for a key papers in their literature review. These presentation will be scheduled completed _November 13th (November 6th)_ unless the author team wants to schedule something earlier.  Early drafts and annotated bibliographies should be distributed before the presentation.

1. A draft of the paper must be published in the “Draft Papers” assignment folder in D2L by _November 19th  (November 12th) at 5 pm_.  Comments returned by November 23rd (November 16th) 8pm.  These comments will need to be addressed in the final paper. If you are writing an empirical paper, the submission should include a link to your data and the code used to analyze the data. 

1. The final paper must be published to the “Final Papers” assignment folder in D2L by _December 4th at 5pm_. Final drafts should be between 15 and 20 pages long, excluding major graphics and bibliography.  Literature review papers should have at least 15 peer reviewed or government publications as part of the review. The submission must include a separate document addressing the issues with the draft paper stating how the point is either irrelevant or how it is addressed in the paper.

# What is a Literature Review?

Knowledge, in the form of an academic paper, does not exist in a vacuum.  It is builds on what is already known, presents new data, and remixes data and results to say something new.  Every academic paper has a literature review to explain where the paper fits in the literature and how it is related to existing knowledge.  Some papers are a wholly a literature review.

A good literature review does not just explain what each paper said;  it has to teach something you wouldn't notice from just reading the papers one-by-one.  It has to provide the conversation between the authors.

## A Walk Through a Litterature Review?

The easiest way to learn what is in a literature review is to look at some that have been published.  A quick google scholar search gives a long listing (https://scholar.google.com/scholar?hl=en&as_sdt=0%2C38&as_vis=1&q=%22energy+economics%22+literature+review&btnG=).  

You can, almost, take one at random.  Say for example Greening, Lorna A., David L. Greene, and Carmen Difiglio. "Energy efficiency and consumption—the rebound effect—a survey." Energy policy 28.6 (2000): 389-401 (http://www.sciencedirect.com.proxy.lib.pdx.edu/science/article/pii/S0301421500000215).

The paper has a solid outline.  It starts with an introduction to the problem and then starts discussion the typology of rebounds.  It is clear that while they were reading the papers they figured out that authors were using "rebound effect" differently and part of the difference in the conclusions was because they were using the same word for many different concepts.  They also noted that the authors were connecting "rebound effects" to other concepts in different ways.

They were making the papers talk to each other about how their definitions and scope was different.  That is something you could not get from reading the individual papers.  They are all about the rebound effect but each one is talking about a slightly different rebound effect.

The empirical evidence section is subdivided logically by end-use, e.g., space heating, and then provides tables summarizing how the data and analysis differ across papers.

Table 1 summarizes method, sample size, effect size, and the existence of control group. Table two gives the years of data, effect size and the scope of data.   The tables are used to frame the discussion that follows. In each case they explain why the papers produced different empirical results and gave reasons for the similarities when they exist.

You can see very similar patterns in the other literature reviews.

In any case, a literature review is not a simple recitation, paper after paper, repeating what each said.  A good literature review adds something.  It provides the conversation between the papers, as if the authors were debating with each other.

# How to Start Your Topic

Don't start with a thesis; start with a paper that you like.  Think of it as a seed.

Later in this document you will see a listing of major journals in the field and you will see a listing of review articles, which are another name for literature review.

Find a paper that you like.  If you are fascinated about urban vs rural differences in household energy use, find a paper that investigates that.  If you want to know if wind generation has an effect on housing prices, find a good paper that investigates that.

In any case, start with a seed paper.

## Find how that paper links to the literature

Every paper comes with its own literature review and its own list of sources -- the bibliography.  

Look at the cited articles and books in the paper you choose.  Those are the papers that the author used to frame their argument and make the case that their contribution was original.  It is also helped the authors frame the research question in their own mind.

After a paper is published, other people will read it and use it to change what they think about the topic.  Many will then cite the seed paper in later works.  Your next step is to look at the papers that cite your seed paper.

Thankfully, Google scholar (https://scholar.google.com) takes care of much of that for you.  It is not the only way to follow the citation chain but it is the most convenient.  Each citation will have a link that gives a listing of the papers that cited that have cited it.

In summary, the bibliography lets you see what led up to the paper, and google scholar lets you see how the world reacted to it.

## Read and Make Notes

Start reading the articles. I don't mean a deep reading.  Use the multi-pass process that that is often called academic skimming:

+ Read the title and abstract
+ Read the section headings
+ Read the introduction
+ Read the conclusion
+ Look at the figures
+ Look at the equations
+ Skim the whole thing
+ Read it but don't freak out if you don't get everything.
    + Keep notes on your reactions, how the topic connects back and questions (My personal notes on papers are filled with profanity)
    + Repeat as time allows.

Academic skimming is what allows faculty to keep up on the literature. It goes faster the more you know about a topic.  It is slow going when you are first learning a topic.  Each paper brings up new issues and new ideas.  After a while you will notice you go faster because fewer of the ideas in the paper are new.  One may be similar to another except the data is from another state.  Another may use a new statistical technique.  The more you know the faster it goes.  

As you read, you will notice that you can start categorizing papers.  There is no one way of categorizing.  You could do it chronologically by decade, or by school of thought, or by statistical technique used, or pro or con, just pick something that works to organize them.

While you are reading make notes.  

+ How are key terms are defined
+ What are some key statistics.
+ Keep an eye out for good quotes.
+ Analyze the papers a bit.  Some are better than others and make notes on why the good ones are good and the bad ones are bad.
+ Look for trends over time on how a topic is treated.  
+ Look for a hole in the literature.  Is there a topic that has been missed?  That would be a great motivation for a later original contribution to the literature.

Once you read enough, you can start to put together a thesis and actually construct a literature review.

##  Where to Find Energy Economics Papers

When we talk about literature reviews we are, generally, talking about review of peer reviewed literature.  This is not about New York Times articles.  This is about written work that has been looked at and criticized by people that really understand the topic.  You can also include well respected think tanks or the publications of large NGOs with respected research and analysis departments, and government publications.

Energy economics is broad and what makes the literature so difficult to approach is that much of it looks like economics but isn't.  A quick way to tell is if the paper looks at behavior, institutions or welfare and cares about uncertainty and causality, it is probably economics. 

Here are some good places to start your reading.  Just skim some titles and see what interests you.

+ Journals that focus on energy economics issues
    + Energy Economics http://www.journals.elsevier.com/energy-economics/
    + The Energy Journal https://www.jstor.org/journal/energyj
    + Resource and Energy Economics http://www.journals.elsevier.com/resource-and-energy-economics/
    + Energy: The International Journal has economics and engineering http://www.journals.elsevier.com/energy/
    + Energy Policy http://www.journals.elsevier.com/energy-policy/
    + Utilities Policy (for more electricity focused reading) http://www.journals.elsevier.com/utilities-policy/

+ Working Paper Sources
    + IDEAS has a curated weekly summary of energy working papers https://ideas.repec.org/n/nep-ene/
    + r/EconPapers has a weekly summary of working papers from National Bureau of Economic Research (NBER).  They usually lead with energy and natural resource economics https://www.reddit.com/r/EconPapers.


# Starting on the Paper

The step-by-step requirements for the term paper is a good model for how to write a literature review.  Empirical papers may start in a different place, but the literature review tends to work fairly lockstep through:

+ Abstract
+ Bibliography
+ Annotated Bibliography
+ First Draft
+ ...
+ Final Draft.

The abstract is the short, elevator pitch, that summarizes your thinking on a topic.

Your abstract will be revised many times before the final draft, but you need a solid abstract before you start just to make sure your topic is paper sized and not something that requires multiple books to treat.  

The usual problem with undergraduates is that they try to write very short papers about very broad topics and end up with a very poor product.

Get narrow. 

Get tractable.

Once you have a reasonable abstract you can start building your literature review.

## But I'm Working on an Empirical Paper

If you want to work with data you still have to create a literature review but it is just part of your paper, not the whole thing.  You still need to situate what you are doing in the existing body of knowledge but after that the steps are a little different.

Chapter 19 of Wooldridge's, "Introductory Econometrics: A Modern Approach" has great advice on how to approach an empirical paper.  The book is on electronic reserve. 

## Bibliography and Annotated Bibliography

Look at the all the papers you have read and decide which ones you want to use in your literature review.  If your answer is "all them", you have not read enough.  Go back and read some more.

The sole exception to this rule is if you doing a meta-analysis, which treats a literature statistically.

Now, it is time to go back over the papers that you listed in the bibliography and construct an annotated bibliography.

### Annotated Bibliography

An annotated bibliography should provide a brief descriptive and evaluative statement about the article and should indicate how you intend to use the paper.

Annotated bibliographies are often not in the usual citation order. You can almost think of this as the first outline of your paper.    

You can organize them according to the argument you intend to make: Statistics, European perspectives, American perspectives, Latin American perspectives, Contrasting the perspectives, for example or chronologically if you are looking at trends over time.

The important part is categorizing the papers according to your argument, pulling out what is important from each, and then figuring out how you will use them in the final paper.

## Write

Just write.  Somewhere down the line you developed a system for getting writing done.  If you are lucky, it is a good system, if not, you have to change it.    

I usually start with a rough outline then add in graphics, tables, and data analysis.  I then add a bunch of details to the the outline, and, once that feels reasonable, start adding paragraphs.

There is no need to write in order.  Pick a part of the outline and write on that topic.  Don't edit it.  Don't try to make it perfect.  Just write.  If every other sentence is good -- fabulous.  The point is to spend a little time each day writing a new section of your paper.  I don't even spell check until I'm done writing for the day.

After you are tired of writing, go back to what you wrote the day before and edit that.

Don't edit anything you wrote that day.  Edit something that you have to read fresh.  Edit something that you don't remember _exactly_ what you meant when you wrote it.  It helps to get you to approach the text like a reader will.

At this point you are getting the idea that writing will take many days. By this time, I know almost all of you will not follow this advice.  

That is the reason that faculty dread term papers. Students bang out a draft the night before and then faculty suffer through poor drafts.

This is not to your advantage.  

The usefulness of my comments is usually proportional to the effort you put into the paper.  If I spot a paper that clearly went from blank page to me in under 24 hours, my comments are very generic and hardly specific to the topic.  They are often are just links back to guidance on how to write a literature review and some ego preserving comments about, 'clearly early work'.  

There is little guidance I can give beyond this because there is so little there.

Good papers, where it is clear that the source material has been read and thought has gone into the argument get the most help.  I edit the paper at the point.  I give missed references.  I clarify and correct your interpretation of statistics.  

I may spend only ten minutes reading and commenting on poorly written paper but I'll spend an hour on a good one.

It short, the less time you put into your paper before it gets to me, the less help you get from me, and the more work you have to do before the final draft.


# Term Paper Resources

Because term papers are rarer than they were in the past, I will be providing a lot of supports to make sure you can pull this off. The subject matter librarian for economics will give a seminar on how to conduct a literature review.  

In addition there are two sources in the library reserve that are very helpful.  First, McCloskey, D. (2000). Economical writing (Second ed.). Prospect Heights, Illinois: Waveland Press. is an excellent read on how to write. There are 31 short, snarky chapters in 91 pages. Read a chapter a day and try to apply what you read and you will be less embarrassed at work.

The second resource in the library reserve is a Chapter 19 in Wooldridge's, "Introductory Econometrics: A Modern Approach". It is a great outline of the process of empirical research.  Graduate students and those attempting an empirical paper should read this before choosing a topic for their term paper.

        
## General Resources

+ A list of energy related glossaries http://dahl.mines.edu/GlossaryLinks.pdf.  Some of the links are 404 but the one at the California Energy Commission is pretty good.
+ EIA Today in Energy (https://www.eia.gov/todayinenergy/) New topics every day.
+ The Journal of Economic Perspectives (https://www.jstor.org/journal/jeconpers) has many easy to read symposia and review articles.  Here are a few from the last decade or so. Some of these are already included in the readings.
    + SYMPOSIUM: OIL AND GAS MARKETS WINTER 2016 (https://www.jstor.org/stable/i40149800)
    + SYMPOSIUM: TRADING POLLUTION PERMITS WINTER 2013 (https://www.jstor.org/stable/i40086192)
    + SYMPOSIUM: ENERGY CHALLENGES WINTER 2012 (https://www.jstor.org/stable/i40064264)
    + SYMPOSIUM: CLIMATE CHANGE SPRING 2009 (https://www.jstor.org/stable/i27740519)

+ Data
    + OpenEI http://en.openei.org/wiki/Main_Page
    + EIA https://www.eia.gov Just go to a topic and look for the data tab.
    + Quandl https://www.quandl.com/ Has data on many topics and is an easy way to bring in macroeconomic data.
    
