---
title: "Introduction"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Plan for the Day

+ Play with Zoom
+ Walk through the syllabus
+ Talk about what is on the micro pre-test
+ Divide up into groups

## Zoom

+ Unmute and mute mic
+ Change your views
+ Show participants
    + Raise hand
    + Speed up
+ Show Chat Window
+ Write on my screen


## Syllabus

You can find the syllabus here and any slide here (https://github.com/woodsjam/Course-Energy-Economics)

+ There is also a link in D2L
+ Some slides are up there but not all.


## Energy Economics

Economics and structure of energy markets, with a focus on electricity. Examines current policy issues arising from energy production and use.

+ We will be looking at energy markets specifically at the start of class, but some of the more interesting topic are in the "consequences of production and use"
    + Is Fracking a "resource curse"?
    + Does development of wind resources have an effect on real estate prices?
+ The field has a mix of:
    + Powerful econometrics
    + Microeconomic theory
    
We will be tuning the class to your level of expertise and filling in the blanks as we go.

## Who Am I?

+ Ph.D. Economist, UC Davis
+ First generation college.
+ Background in energy conservation and program evaluation consulting going back to the early 90s.
    + Projects were multidisciplinary. Rarely did a project not involve, economists, engineers and others.
    + ETO external review committee
    + I have steel toed boots.
    
+ Former:
    + Oregon HECC commissioner
    + Parkrose School Board Chair
    + Multiple non-profit boards
    + County Budget Committees
    + Legislative Candidate.
+ Hobbies: Painfully Stereotypical Portlander

    
## Warnings

+ I'm Dyslexic.  If you see a slide without a typo -- be amazed.
+ Don't think that you have to understand everything
    + You should read everything.
    + I usually read things over and over again and learn new things every time.
    + If you understand half -- amazing.
    + The more you read, the easier it is to learn more.  It really builds on itself.

## Warnings (Con't)

+ Don't be afraid to Google a picture or an article to help you understand something in class.
    + You need to learn how to help yourself.
    + Learned helplessness is a pet peeve of  mine.
+ Do not wait till the last minute  
    + Don't make an optimistic, tightly scheduled plans.
    + No plan survives contact with reality
    + Start everything as early as possible.


## Where can you take this knowledge

+ Energy Efficiency evaluation and implementation
    + Plenty of local firms do this (Many former students)
    + Energy Trust of Oregon (ETO)
    + Northwest Energy Efficiency Alliance (NEEA)
+ Utilities
    + Northwest Natural 
    + PGE, Pacificorp
+ Government
    + Oregon department of energy
    + PUC
    + Many opportunities as/if Cap and Trade takes off
+ Other For Profit
    + Anything related to home automation.
    + Use off high frequency meter data.
    + Carbon Offset certification and evaluation.
    
## Look at Course Requirements and the Syllabus

A few things of note

+ There is a term paper.
+ Reading discussion with some outside prep.
+ My contention is that if you are good with theoretical models or empirical models or explaining them to others, you are employable.
    + The last one is frequently forgotten.
    + They are often the highest fliers in the industry.


## Prerequisites

+ Undergrad Students: EC 311/415
+ Graduate Students: NONE except graduate standing

The usual pattern is the undergrads are econ majors and know 201 material and some 311.  Grad students tend to be engineers with less econ but more math than the undergrads.


## Contact Information

+ There are no in-person office hours this term.  We will use Zoom to meet face-to-face. 
+ Drop in office hours are Monday 3-4pm and Tuesday 10am-Noon through the last week of classes. I will keep a Zoom meeting up during this time.
+ You can schedule one-on-one meetings at https://woodsj.youcanbook.me/.

Meetings can be via phone or even the hangout/meet function in your pdx.edu email.

I will also keep Slack up during office hours to answer questions.

## Slack

I avoid email since it is a trash heap and a constant distraction.

+ The class will use slack https://psuenergyecon.slack.com
+ Handles direct messages, forum style responses.
+ You should be able to sign up with your pdx.edu account
+ Can access via webpage, apps in Android and iOS.
+ Linked in d2l.
+ Officially supported PSU software
+ Common in industry
+ Many of you already use it.

## Hints on Slack

+ Prefer #general to direct messaging me.
    + Questions about course material is for #general
    + Questions about your grade or anything private is for @jamie woods
+ "I can't find it anywhere" is often answered with:
    + A link to a google search.
    + Link to material in syllabus or github resources.
+ Don't start and end with, "I got 7 but the key shows 245.  What did I do wrong?"
    + Show your work.  The fix is often a single parameter.
+ Provide full text of the question you are working on.

In short, make it easy for someone to help you.


## Textbook and Other Material


Dahl, Carol. _International Energy Markets: Understanding Pricing, Policies, & Profits._ PennWell Books, 2015.


+ The remaining material is all links in d2l.  Most of those links go to the library.
+ The intent is to keep cost down

## Assessments and Grade Policy

+ Discussion and Assignments (in total): 43%
+ Final Draft of Term Paper: 20%
+ Draft Term Paper: 15%
+ Presentation of Paper Topic: 15%
+ Annotated Bibliography: 3%
+ Abstract: 2%
+ Writing Sample: 2%


Basically, the questions about the material before class and in-class discussion is 43% of your grade and the rest is term paper.

## What a Class Meeting Looks Like

+ You read the material ahead of time.
+ Answer some questions on the material in d2l
+ There may be a short framing lecture
+ Break into discussion groups.
+ Questions randomly given out
+ Each group has a scribe that will summarize discussion in a shared google doc for the class
+ I bounce from group to group pushing conversation to make sure y'all have actual read the material
+ Share out and take questions from other groups.
+ After class feedback from you on who did best and worst in the group.

## Yes, There are Groups, But

+ Team members can be removed by an anonymous simple majority vote.
+ The removed student acts as a group of one until others are removed from their group.

## The Reading Questions

+ Students tend not to read when things aren't directly incented.
+ Microeconomic theory questions, interpretations of graphs and regression output in papers, etc.
+ These will be due at the start of the class to avoid any confusion.

## The Term Paper

+ Literature review or empirical paper
+ Lit Reviews are single author.
+ Empirical, which means econometrics and data handling, may have up to three authors.
+ At least 15 pages but under 20 pages, not including bibliography and major graphics.

The intent is to be able to take it to a conference or use as evidence that you can write when looking for a job.  Guidance documents on github

## Help?

+ Handout from me.
+ Syllabus has links to major journals and working paper archives that cover energy.
+ A few hint books.  McCloskey for all and one chapter from Wooldridge's econometrics book for those doing empirical papers. 


## The Term Paper Schedule

1. Writing Sample: _October 7th at 5pm_. Graded by October 9th at 5pm
1. Draft Abstract: _October 18th (October 14th) at 5pm_. Comments returned at Abstract Review Meeting.
1. 20-minute Abstract Review: _October 23rd (October 20th) at 5pm_.
1. Revised Abstract: _October 28th (Oct 22) at 5pm_.
1. Annotated bibliography: _November 6th (October 30th)  at 5pm_. Comments returned by November 9th (November 2nd) at 8pm
1. 20-Minute Presentation: _November 13th (November 6th)_.
1. Draft Paper: _November 19th  (November 12th) at 5 pm_.  Comments returned by November 23rd (November 16th) 8pm.
1. Final Paper: _December 4th at 5pm_. 


## Big Note

Step one is the writing sample.  If it looks good, great.  If not,

+ All the deadlines move up a week so you have more time between the draft and final paper.
+ You have to schedule time in the writing center at each step.

## What Grades Looked Like Last Time


+ 10 students received As. Two of these students had their paper accepted at a conference. That paper informed PGE's Electric School Bus Project, an ongoing pilot to convert school buses from diesel to electric and support the electric grid in the summer.
+ One student received a C.  The student turned in a low-quality term paper, attended fewer classes than the students that received As but showed little evidence of having read the material.

## Then there was this

+ Three received Fs after attending fewer than half the classes and turning in very low-quality term papers that resulted from not paying attention to the term paper requirements, feedback on what they wrote, and advice on how to improve the paper.
+ Three students received Incompletes (I) because they did not turn in a term paper but otherwise had acceptable work and would pass the course if they turned in the term paper. 

## P/NP Grades

+ You can take the class P/NP for your major and it counts.
+ No guarantee how outsiders will interpret the P
+ We expect an asterisk on 2020 grades.
+ Consult your funder for financial implications


## 

Now that we are done pretending everything will be normal and nothing odd will happen.


## COVID-19

+ Added flexibility to deal with a certain level whatever you call it.
+ Two systems
    + A system for reading and discussion
    + A separate system for the term paper.
+ The final step in both is a deadline appeal.

## You are sick but it is less than two weeks

+ Notify (@woodsj or woodsj@pdx.edu) me.
+ Do that every day you are out.
+ Keep up with reading and turn in assignments if you think you are doing at least as well as usual. No harm if you don't

## You survived

+ Notify (@woodsj or woodsj@pdx.edu) me.
+ Set a meeting on https://woodsj.youcanbook.me/ for each reading you missed.
+ Study the readings.
+ Pass your one-on-one conference on the reading for credit

## Term Paper Flexibility

You missed at least two but less than four classes in a row.

Pick a solution:

+ **Situation Normal**: No changes to deadlines.
+ **I Can Recover**: Deadlines pushed back a week except the final paper which is due three days later. 
+ **Put This Over Here With the Rest of the Fire**:  All deadlines pushed back two weeks except the final draft which is due September 1st, 2021.  There is an I on transcript till you complete.

Tell me after you schedule your reading conference.  You can start closer to the FIRE end and de-escalate but not the other way.


##  The Last Gasp

Sick for more than two weeks

+ Deadline appeal
+ Money back, class off the transcript.
+ Check financial implications before you do this.
+ Requires documentation.


## Jamie Gets Sick

I'm the guy that gets grades in banweb first so in case I die it won't screw up your financial aid.

+ PSU has no plan for this.
+ Jose, the GA, can handle discussion if I have the questions written ahead of time.
+ If I'm out more than a week, I will contact the chair about a plan.

## Please Be Kind to Me

+ I basically left my calendar open and gave you time flexibility
+ Don't be strategic in missing days to delay readings
+ Don't show up unprepared and 'hope for the best'


## Questions    


## Lets talk about the pre-test and why

+ Does not count for your grade
+ Don't freak out if you can't do all of it.
+ I need it to dial in questions and lecture
+ The department needs it to see how well we are teaching.

## Lets Break Into-Groups

+ In chat, who did you have for 311/415? Grad students say your last econ class.
+ Have you taken econometrics?
+ Last math and stats class?

## Reading for Next Monday

+ Read Dahl Ch 1-2.  It is about 40 pages.
+ "Energy Primer: A Handbook of Energy Market Basics", Ch 1.  About 3 pages
+ DON'T PANIC

## Wednesday is the pre-test

+ Utility maximization:
    + Diagrams with indifference curves and budget constraints.
    + What happens when prices change
+ Profit maximization:
    + Relationship between AC, MC, AVC, MR, D
    + Profit maximizing output, revenue, fixed and variable costs, profit.
+ Reading regression output
+ Some math

## Learn How to Read

It is a multipass system typically called academic skimming

+ Read the Title and abstract (Papers)
+ Read the section headings
+ Read the introduction
+ Read the conclusion
+ Look at the figures
+ Look at the equations
+ Skim the whole thing
+ Read it but don't freak out if you don't get everything.
    + Keep notes on your reactions, how the topic connects back and questions 
    + Repeat as time allows.

You, and the author, will never fully understand the paper/chapter.
