---
title: "Culver2016CoalDecline"
author: "James Woods"
date: "10/11/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Culver, Walter J., and Mingguo Hong. "Coal’s decline: Driven by policy or technology?." The Electricity Journal 29.7 (2016): 50-61. http://stats.lib.pdx.edu/proxy.php?url=http://www.sciencedirect.com/science/article/pii/S104061901630121X 


+ Is it EPA rules?
    + Same as 1990. 
    + Scrubbers cost $.01 to $.03/MMBTU for even high sulfur Appalachian and Illinois coal.
    + Powder River is cheaper still.
    + Total cost of gen was  $2.76–$4.60/MMBtu 
    + CPP is still waiting decision. September 27, 2016, the case against the CPP was heard in the United States Court of Appeals for the District of Columbia Circuit.
+ So shale gas.
    + 2014, of the 27.3 Tcf from all gas sources, shale gas reached 13.4 Tcf – 10.4 times the level of 2007 – and dropped to half the price.
    + Cheaper than coal because less than $3.5/MMBTU.
    + Transport cost is $.03 per ton mile over 2k mile route.  
    + New pipelines for gas unify and reduce volatility of non HH gas.

+ PJM and others are making it hard
    + Capacity Performance (CP) rule penalties if you don't produce as a resource (extra payment to you if you sign up) when assets go offline or demand goes up.
    + Factoid 30 amortization life for gas gen plants. 50 year life

+ But what if power plants
    + Energy per capita fall 0.4% per year
    + Energy per real gdp falls 2% per year.
    + Power plants can't drive up the price.
+ But what if  exports
    + LNG could be anything but prices must be high to happen.
    + Mexico pipeline is still 2% of production at best.
    + Even the bankruptcies are not a problem.  Makes it cheaper for those that buy assets.
    
+ Renewables?
    + three quarters of the states have renewable portfolio standards (RPS) or renewable portfolio goals, the former (80% of them) being enforceable.
    + As of 2015, batteries served just 187 megawatts (MW) out of 350,000 MW of storage-addressable grid.
    + Gas Advantages
        + High ramp rate 40MW/min
        + Better heat rate. CCGT 8500 BTU/kWh to 5600 coal is still 1000 BTU/kWh. 3412 is perfect
    