---
title: "Notes on Joskow 2013 Natural Gas"
author: "James Woods"
date: "10/11/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Joskow, Paul L.. 2013. "Natural Gas: From Shortages to Abundance in the United States." American Economic Review, 103(3): 338-43. http://stats.lib.pdx.edu/proxy.php?url=https://www.aeaweb.org/articles?id=10.1257/aer.103.3.338


+ FERC predecessor attempted to use rate of return regulation at the wellhead.  Bad idea for wellheads that traded within state (free market) and when dealing with associated gas.
    + 1978 NGPA, check the FERC tariff page for this, did this odd blending of vintages pricing when selling to LDCs.
    
+ Second  oil shock 79-80 ran up oil prices and there was massive switch to gas.
    + take or pay contracts at high prices were result.
    + Oil fell to 2/3 of peak in 86 and prices stayed high with expected excess supply.
    + Many switched to oil and coal.
    + the market unbundled gas from transport. Buying pipeline transport rights and buying direct from wellhead.
    + FERC formalized this with 436, 500 and 636 (1992).
    + Natural Gas Wellhead Decontrol Act of 1989.
        + killed intra and interstate regulation 
        + Gave modern structure of posted prices.
+ 1990s
    + Henry Hub develops and basis differences decline.
    + More imports start to happen from CA and from AK.
+ 2000s
    + LNG becomes a way to import as demand increases.
    + 2010 Shale gas 5 TCF.
+ Shale Gas
    + Deep, 1k to 13K feet.
    + Tech advances made possible
        + Deep drilling
        + Horizontal drilling
        + Fracking for horizontal
        + Telemetry, the visualization component
    + Nice short tech description.
+ Boom Effects
    + Local
    + Cheap gas
    + More electricity plants running, higher capacity factors. 50 to 60% rather than 30%
    + Fewer coal plants in use, and 50% less CO2.
    + Not import dependent.
+ Environment
    + Coming soon to areas without experience regulating gas.  They must develop their own.
    + Drinking water contamination is probably well casing failure and not the gas itself.
    + Probably masks other effects.
        + waste water and storage of water.
        + Methane release.
        + Regulation still behind
        
        
+ Reflection
    + Reg and enforcement of well construction standards and water storage are most important to address.
    + Methane leaks may undo all CO2 reductions from reduction in coal fired plants.