---
title: "Intro to DER"
author: "James Woods"
date: "11/20/2016"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## DER vs DG

+ DG = Distributed Generation
+ DER = DG + Storage

May seem like semantics but small storage grew in potential since 2005

##  What is in DER

+ Definitions vary but Small (< 49MW) generation seems to count with < 1MW most common.
    + Plenty of renewable
    + Small turbine
    + Backup generators
    + Battery banks.
+ Combined Heat and Power
    + Steam Generation
    + Chill Water
    + District Energy
    
## Why Would I (Private) Build It?

+ Power Quality
    + Equipment is sensitive to voltage drops or spikes
    + Equipment is sensitive to frequency variation.
    + Wave shape and harmonics
    + High reactive power needs (Often avoids utility charge.)
    
+ Reliability (Often combined with quality)
    + High cost of interrupted power, e.g., hospital
    + Two common measures 
        + System Average Interruption Duration Index (SAIDI), average total time without power over a year.
        + Customer Average Interruption Duration Index (CAIDI), average time without given your power is out.
        + Many more relating to frequency and cost of lost service.
    + You could have lower rates if you have an interruptible tariff.    


## Why Would I (Private) Build It? (Cont)

+ Peak reduction
    + If you have demand (kW) charges, your maximum use.
    + If you have a coincident peak (kW) charge, you use at system peak.

+ Cogeneration Opportunity
    + Already need Steam or Chill water
    + Electricity generation is a bonus
      
+ Reduction in volumetric (kWh) charges
    + Net metering just a bit to shave off the high block charges
    + Peak Pricing Tariff
    + Real-time Prices.
    + Nice subsidy.
    + Actually, social cost, cheaper.
    
+ The utility side is significantly more complicated.

## Three simple ways of thinking about costs

+ The Make vs Buy trade-off (TC).
+ The Minimum Efficient Scale (AC), i.e., volume such that AC is at a minimum.
+ Investment Delay, a time value of money concept.

With all cost estimates the key conceptual problem is to only look at incremental costs.

+ It is often unclear what those incremental costs are relative to.  
+ Cost does depend on your point of view.

## Example Make vs Buy

+ Assume cost functions of $C = F + \alpha q$ form.  
    + Fixed cost
    + Constant average variable cost
+ Make vs Buy:  Given known q, Choose the least cost technology 

## Example MES

+ Several definitions of MES
    + Quantity such that $MC=AC$.
    + Quantity such that AC decreases very little as quanity increases.

## Example Investment Delay

+ Pushing costs into the future can be valuable.
+ Value of delay increases as interest rates increase.
+ Exponential discounting $P = \frac{F}{(1+i)^N}$.


+ Example:  Maintanace expenditures of $100 a year forever. What is the value of skipping a year?
    + $PW(Maintance) = \frac{100}{i}$ At i = 10% this is `r 100/.1`.
    + Delay for 1 year is $\frac{\frac{100}{i}}{1+i}$. This is `r round((100/.1)/1.1,2)`. 
    + The difference is the savings.

## How Did We Get to the Current G-T-D Arrangment (MES Argument)

+ Both large scale and small scale originally existed.
+ Large scale developed
    + Lower AC
    + Higher MES
    + Speed of change up till 60s made this the dominiate form.
+ Small scale continued to develop
    + Right sized scale and MES
    + Decreasing AC
    + 1978 Qualifying Facilities Era was when they could sell power under some conditions.

## Private Choice of Technology (Make vs Buy Argument)

+ Have access to utility power and DG.
+ Several States of Opportunity Costs
    + If you have no special needs and need to pay full cost of fuel.
    + If you have 'Free' access to fuel, e.g., wood chips, AC of DG is lower.
    + If power quality or interuption is not what is desired, AC of utility power is higher.
    + If you face a Peek, Time of Use or Demand Charge.
    + More complicated diagrams can be made but this works.

    
    
## Utility Point of View 

Please note that lots of power quality issues need to be solved on the D side, with capacitors and transformers. Power quality may actually get worse with new equipment and DG.

+ Utility: Supply customer needs with T+G or with DG. Tradeoffs between the two in an isoquant/isocost sense.
+ Customer: Decide to take utility solution or provide with private DG. (Make vs Buy).


